server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/GangwarDinesh/config-store
          username: dineshgngwr@gmail.com
          passphrase: Gangwar@1.
